program Rp;

uses
  Vcl.Forms,
  Rp.View.Principal in 'src\view\Rp.View.Principal.pas' {FrmPrincipal},
  Rp.View.Base in 'src\view\base\Rp.View.Base.pas' {FrmBase},
  Rp.View.Base.Pesquisa in 'src\view\base\Rp.View.Base.Pesquisa.pas' {FrmBasePesquisa},
  Rp.View.Pesquisa.Cidade in 'src\view\Pesquisa\Rp.View.Pesquisa.Cidade.pas' {FrmPesquisaCidade},
  Rp.Controller in 'src\controller\Rp.Controller.pas',
  Rp.Controller.Cidade in 'src\controller\Rp.Controller.Cidade.pas',
  Rp.Model.Entity.Cidade in 'src\model\entity\Rp.Model.Entity.Cidade.pas',
  Rp.Model.List.Cidade in 'src\model\List\Rp.Model.List.Cidade.pas',
  Rp.Model.Dao.Generic in 'src\model\dao\Rp.Model.Dao.Generic.pas',
  Rp.Model.List.Generic in 'src\model\list\Rp.Model.List.Generic.pas',
  Rp.Model.Rest in 'src\model\Rp.Model.Rest.pas',
  Rp.View.Base.Cadastro in 'src\view\base\Rp.View.Base.Cadastro.pas' {FrmBaseCadastro},
  Rp.View.Cadastro.Cidade in 'src\view\cadastro\Rp.View.Cadastro.Cidade.pas' {FrmCadastroCidade},
  Rp.Util.Types in 'src\util\Rp.Util.Types.pas',
  Rp.Util.Funcoes in 'src\util\Rp.Util.Funcoes.pas',
  Rp.View.Mensagem in 'src\view\Rp.View.Mensagem.pas' {FrmMensagens},
  Rp.View.Cadastro.Bairro in 'src\view\cadastro\Rp.View.Cadastro.Bairro.pas' {FrmCadastroBairro},
  Rp.Model.List.Bairro in 'src\model\list\Rp.Model.List.Bairro.pas',
  Rp.Model.Entity.Bairro in 'src\model\entity\Rp.Model.Entity.Bairro.pas',
  Rp.Controller.Bairro in 'src\controller\Rp.Controller.Bairro.pas',
  Rp.View.Pesquisa.Bairro in 'src\view\pesquisa\Rp.View.Pesquisa.Bairro.pas' {FrmPesquisaBairro},
  Rp.Controller.Cliente in 'src\controller\Rp.Controller.Cliente.pas',
  Rp.Controller.Funcionario in 'src\controller\Rp.Controller.Funcionario.pas',
  Rp.Model.Entity.Cliente in 'src\model\entity\Rp.Model.Entity.Cliente.pas',
  Rp.Model.Entity.Funcionario in 'src\model\entity\Rp.Model.Entity.Funcionario.pas',
  Rp.Model.List.Cliente in 'src\model\list\Rp.Model.List.Cliente.pas',
  Rp.Model.List.Funcionario in 'src\model\list\Rp.Model.List.Funcionario.pas',
  Rp.View.Pesquisa.Cliente in 'src\view\pesquisa\Rp.View.Pesquisa.Cliente.pas' {FrmPesquisaCliente},
  Rp.View.Pesquisa.Funcionario in 'src\view\pesquisa\Rp.View.Pesquisa.Funcionario.pas' {FrmPesquisaFuncionario},
  Rp.View.Cadastro.Cliente in 'src\view\cadastro\Rp.View.Cadastro.Cliente.pas' {FrmCadastroCliente},
  Rp.View.Cadastro.Funcionario in 'src\view\cadastro\Rp.View.Cadastro.Funcionario.pas' {FrmCadastroFuncionario},
  Rp.Model.Entity.FormaPagamento in 'src\model\entity\Rp.Model.Entity.FormaPagamento.pas',
  Rp.Model.Entity.Servico in 'src\model\entity\Rp.Model.Entity.Servico.pas',
  Rp.Model.List.FormaPagamento in 'src\model\list\Rp.Model.List.FormaPagamento.pas',
  Rp.Model.List.Servico in 'src\model\list\Rp.Model.List.Servico.pas',
  Rp.View.Pesquisa.FormaPagamento in 'src\view\pesquisa\Rp.View.Pesquisa.FormaPagamento.pas' {FrmPesquisaFormaPagamento},
  Rp.View.Pesquisa.Servico in 'src\view\pesquisa\Rp.View.Pesquisa.Servico.pas' {FrmPesquisaServico},
  Rp.View.Cadastro.Servico in 'src\view\cadastro\Rp.View.Cadastro.Servico.pas' {FrmCadastroServico},
  Rp.View.Cadastro.FormaPagamento in 'src\view\cadastro\Rp.View.Cadastro.FormaPagamento.pas' {FrmCadastroFormaPagamento},
  Rp.Controller.FormaPagamento in 'src\controller\Rp.Controller.FormaPagamento.pas',
  Rp.Controller.Servico in 'src\controller\Rp.Controller.Servico.pas',
  Rp.View.Base.Movimento in 'src\view\base\Rp.View.Base.Movimento.pas' {FrmBaseMovimento},
  Rp.View.Movimento.Venda in 'src\view\movimento\Rp.View.Movimento.Venda.pas' {FrmMovimentoVenda},
  Rp.View.Pesquisa.Venda in 'src\view\pesquisa\Rp.View.Pesquisa.Venda.pas' {FrmPesquisaVenda},
  Rp.Controller.Venda in 'src\controller\Rp.Controller.Venda.pas',
  Rp.Controller.VendaParcela in 'src\controller\Rp.Controller.VendaParcela.pas',
  Rp.Controller.VendaServico in 'src\controller\Rp.Controller.VendaServico.pas',
  Rp.Model.Entity.Venda in 'src\model\entity\Rp.Model.Entity.Venda.pas',
  Rp.Model.Entity.VendaParcela in 'src\model\entity\Rp.Model.Entity.VendaParcela.pas',
  Rp.Model.Entity.VendaServico in 'src\model\entity\Rp.Model.Entity.VendaServico.pas',
  Rp.Model.List.Venda in 'src\model\list\Rp.Model.List.Venda.pas',
  Rp.Model.List.VendaParcela in 'src\model\list\Rp.Model.List.VendaParcela.pas',
  Rp.Model.List.VendaServico in 'src\model\list\Rp.Model.List.VendaServico.pas',
  Rp.View.Movimento.VendaPagamento in 'src\view\movimento\Rp.View.Movimento.VendaPagamento.pas' {FrmMovimentoVendaPagamento},
  Rp.View.Busca.Cliente in 'src\view\busca\Rp.View.Busca.Cliente.pas' {FrmBuscaCliente},
  Rp.View.Base.Busca in 'src\view\base\Rp.View.Base.Busca.pas' {FrmBaseBusca},
  Rp.View.Busca.Cidade in 'src\view\busca\Rp.View.Busca.Cidade.pas' {FrmBuscaCidade},
  Rp.View.Busca.Bairro in 'src\view\busca\Rp.View.Busca.Bairro.pas' {FrmBuscaBairro},
  Rp.View.Busca.Servico in 'src\view\busca\Rp.View.Busca.Servico.pas',
  Rp.View.Login in 'src\view\Rp.View.Login.pas' {FrmLogin},
  Rp.Util.Variables in 'src\util\Rp.Util.Variables.pas',
  Rp.Controller.Usuario in 'src\controller\Rp.Controller.Usuario.pas',
  Rp.Model.Entity.Usuario in 'src\model\entity\Rp.Model.Entity.Usuario.pas',
  Rp.Model.List.Usuario in 'src\model\list\Rp.Model.List.Usuario.pas',
  Rp.Model.Session in 'src\model\Rp.Model.Session.pas',
  Rp.Controller.Login in 'src\controller\Rp.Controller.Login.pas',
  Rp.Model.Dao.Login in 'src\model\dao\Rp.Model.Dao.Login.pas',
  Rp.Controller.MovimentoServico in 'src\controller\Rp.Controller.MovimentoServico.pas',
  Rp.Controller.Movimento in 'src\controller\Rp.Controller.Movimento.pas',
  Rp.Model.Entity.Movimento in 'src\model\entity\Rp.Model.Entity.Movimento.pas',
  Rp.Model.Entity.MovimentoServico in 'src\model\entity\Rp.Model.Entity.MovimentoServico.pas',
  Rp.Model.List.Movimento in 'src\model\list\Rp.Model.List.Movimento.pas',
  Rp.Model.List.MovimentoServico in 'src\model\list\Rp.Model.List.MovimentoServico.pas',
  Rp.View.Movimento.OrdemServico in 'src\view\movimento\Rp.View.Movimento.OrdemServico.pas' {FrmMovimentoOrdemServico},
  Rp.View.Pesquisa.OrdemServico in 'src\view\pesquisa\Rp.View.Pesquisa.OrdemServico.pas' {FrmPesquisaOrdemServico},
  Rp.Model.Request in 'src\model\Rp.Model.Request.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  ReportMemoryLeaksOnShutdown := True;
  Application.CreateForm(TFrmPrincipal, FrmPrincipal);
  Application.Run;
end.
